# Generated by Django 4.2.24 on 2026-06-19 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import horilla.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRMeetingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('meeting_date', models.DateField(verbose_name='Date')),
                ('purpose', models.CharField(max_length=255, verbose_name='Purpose of Meeting')),
                ('discussion', models.TextField(blank=True, null=True, verbose_name='Discussion')),
                ('solutions', models.TextField(blank=True, null=True, verbose_name='Solutions')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=horilla.models.upload_path, verbose_name='Attachment')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('people_involved', models.ManyToManyField(related_name='hr_meeting_records', to='employee.employee', verbose_name='People Involved')),
            ],
            options={
                'verbose_name': 'HR Meeting Record',
                'verbose_name_plural': 'HR Meeting Records',
                'ordering': ['-meeting_date'],
            },
        ),
    ]
