# Generated by Django 4.2.24 on 2026-07-20 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('base', '0003_alter_employeeshiftschedule_auto_punch_out_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='wage',
            field=models.FloatField(default=0, null=True, verbose_name='CTC'),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='wage',
            field=models.FloatField(default=0, null=True, verbose_name='CTC'),
        ),
        migrations.CreateModel(
            name='SpecialBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('bonus_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Reason')),
                ('company_id', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_bonuses', to='employee.employee', verbose_name='Employee')),
                ('given_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_bonuses_given', to='employee.employee', verbose_name='Given By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Special Bonus',
                'verbose_name_plural': 'Special Bonuses',
                'ordering': ['-bonus_date'],
            },
        ),
    ]
