# Generated by Django 4.2.24 on 2026-07-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeshiftschedule',
            name='auto_punch_out_time',
            field=models.TimeField(blank=True, help_text='Time at which the Tiltas Systems LLP will automatically check out the employee attendance if they forget.', null=True, verbose_name='Automatic Check Out Time'),
        ),
    ]
