# Generated by Django 4.2.24 on 2026-07-16 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
        ('geofencing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='geofencing',
            name='unique_company_id_when_not_null_geofencing',
        ),
        migrations.AddField(
            model_name='geofencing',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='geofencing',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geo_fencing', to='base.company'),
        ),
    ]
