# Generated by Django 4.2.24 on 2026-06-20 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceImprovementPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('reason', models.TextField(verbose_name='Reason / Performance Issues Observed')),
                ('objectives', models.TextField(verbose_name='Objectives / Expected Improvements')),
                ('support_provided', models.TextField(blank=True, null=True, verbose_name='Support to be Provided')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('extended', 'Extended'), ('terminated', 'Terminated')], default='draft', max_length=20, verbose_name='Status')),
                ('outcome_notes', models.TextField(blank=True, null=True, verbose_name='Outcome / Closing Notes')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pip_plans', to='employee.employee', verbose_name='Employee')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Performance Improvement Plan',
                'verbose_name_plural': 'Performance Improvement Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PIPProgressReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('review_date', models.DateField(verbose_name='Review Date')),
                ('progress_notes', models.TextField(verbose_name='Progress Notes')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('pip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='pip_management.performanceimprovementplan', verbose_name='PIP')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pip_reviews_conducted', to='employee.employee', verbose_name='Reviewed By')),
            ],
            options={
                'verbose_name': 'PIP Progress Review',
                'verbose_name_plural': 'PIP Progress Reviews',
                'ordering': ['-review_date'],
            },
        ),
        migrations.CreateModel(
            name='PIPGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Goal Description')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='Target Date')),
                ('is_achieved', models.BooleanField(default=False, verbose_name='Achieved')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='pip_management.performanceimprovementplan', verbose_name='PIP')),
            ],
            options={
                'verbose_name': 'PIP Goal',
                'verbose_name_plural': 'PIP Goals',
                'ordering': ['created_at'],
            },
        ),
    ]
